KEYWORDS = [
    "cinematic",
    "colorful background",
    "concept art",
    "dramatic lighting",
    "high detail",
    "highly detailed",
    "realistic",
    "intricate",
    "sharp details",
    "octane render",
    "smooth",
    "studio lighting",
    "trending on artstation",
    "national geographic",
    "photography",
    "photo",
    "portrait",
    "50mm portrait photography",
    "ultrarealistic",
    "award winning photo",
    "80mm lense",
    "render",
    "masterpeice",
    "breathtaking",
    "superb",
    "groundbreaking",
    "outstanding",
    "photoshop",
    "unreal engine",
    "hd",
    "artstation",
    "8k",
    "4k",
]

WEIGHTS = ["test"]
